import {afterEach,describe,expect,it,vi} from 'vitest'
import {createHimotokiAccount,SignInRequiredError,type HimotokiSession} from './himotokiAccount'
const json=(body:unknown,status=200)=>Response.json(body,{status})
const session=(uid='a',expired=false):HimotokiSession=>({uid,email:`${uid}@example.test`,displayName:uid,photoUrl:'',idToken:`id-${uid}`,refreshToken:`refresh-${uid}`,expiresAt:expired?0:Date.now()+3600000})
function pending(){let resolve!:(r:Response)=>void;return {promise:new Promise<Response>(r=>resolve=r),resolve:(r:Response)=>resolve(r)}}
function setup(fetcher:any,expired=false){let current:HimotokiSession|null=session('a',expired);return {account:createHimotokiAccount({apiKey:'test',projectId:'himotoki',fetch:fetcher,storage:{get:async()=>current,set:async(s)=>{current=s},remove:async()=>{current=null}},launchAuthFlow:async()=>undefined,redirectUrl:'https://test.chromiumapp.org/'}),get:()=>current,set:(s:HimotokiSession|null)=>{current=s}}}
afterEach(()=>vi.restoreAllMocks())
describe('audit: actual account lifecycle',()=>{
 it('late refresh restores account A after sign-out',async()=>{const p=pending();const fetcher=vi.fn().mockReturnValueOnce(p.promise).mockImplementation(async()=>json({fields:{},updateTime:'t'}));const s=setup(fetcher,true);const save=s.account.addFavorite({seq:1,headword:'猫'});await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(1));await s.account.signOut();expect(s.get()).toBeNull();p.resolve(json({id_token:'renewed-a',refresh_token:'new-a',expires_in:'3600'}));await save;expect(s.get()?.uid).toBe('a');console.log('After sign out + old refresh:',s.get()?.uid)})
 it('old invalid refresh clears account B',async()=>{const p=pending(),fetcher=vi.fn().mockReturnValueOnce(p.promise),s=setup(fetcher,true);const caught=s.account.addFavorite({seq:1,headword:'猫'}).catch(e=>e);await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(1));s.set(session('b'));p.resolve(json({error:{message:'INVALID_REFRESH_TOKEN'}},400));expect(await caught).toBeInstanceOf(SignInRequiredError);expect(s.get()).toBeNull();console.log('New account B after old refresh fails:',s.get())})
 it('a save begun in A commits private context into B after account switch',async()=>{const p=pending(),calls:{url:string,init:any}[]=[];const fetcher=vi.fn(async(url:any,init:any={})=>{calls.push({url:String(url),init});return calls.length===1?p.promise:json({fields:{},updateTime:'b1'})});const s=setup(fetcher);const save=s.account.addFavorite({seq:123,headword:'猫',contextSentence:'Private sentence selected under A'});await vi.waitFor(()=>expect(calls).toHaveLength(1));s.set(session('b'));p.resolve(json({error:{message:'NOT_FOUND'}},404));await save;expect(calls[0].url).toContain('/saved/a');expect(calls[1].url).toContain('/saved/b');expect(calls[1].init.body).toContain('Private sentence selected under A');console.log('Read A then wrote to:',calls[1].url)})
 it('refresh HTTP429 deletes usable session',async()=>{const fetcher=vi.fn().mockResolvedValue(json({error:{message:'TOO_MANY_REQUESTS'}},429)),s=setup(fetcher,true);await expect(s.account.addFavorite({seq:1,headword:'猫'})).rejects.toBeInstanceOf(SignInRequiredError);expect(s.get()).toBeNull();console.log('Session after HTTP429:',s.get())})
})
